InventoryImage:
  #Whether or not to generate images for the item placeholder
  Item:
    EmbedDisplay: 
      Single: "{Item}"
      Multiple: "{Item} x{Amount}"
    Enabled: true
  #Whether or not to generate images for the inventory placeholder
  Inventory:
    #Use the player inventory gui template instead of the normal inventory template
    UsePlayerInventoryView: true
    EmbedColor: "#55FFFF"
    Enabled: true
  #Whether or not to generate images for the enderchest placeholder
  EnderChest:
    EmbedColor: "#FF55FF"
    Enabled: true

HoverEventDisplay:
  #Whether or not to show hover event text
  Enabled: true
  #Whether or not to show the cursor image
  ShowCursorImage: true
  #Which custom placeholder should have their hover event text ignored
  #This is a list of integer by indexes
  IgnoredPlaceholderIndexes: []

DiscordAttachments:
  #Whether or not to convert discord attachments from diguesting urls into clickable text in chat
  Convert: true
  Formatting: 
    Text: "&e[&b{FileName}&e]"
    ImageOriginal: " &a(Link)"
    Hover:
      Enabled: true
      HoverText: 
        - "&bClick to View"
      ImageOriginalHover: 
        - "&eOpen Original"
  #Whether or not to allow previwing images in game using maps
  ShowImageUsingMaps: true
  Timeout: 86400

DiscordMention:
  #Link mentions through discordsrv linked accounts
  TranslateMentions: true

  #The sound to play when a player is mentioned
  #https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  MentionedSound: ENTITY_EXPERIENCE_ORB_PICKUP

  #The title to show when mentioned
  MentionedTitle: "&c&lMentioned"

  #How long should the title be shown when mentioned
  #Duration in seconds
  MentionedTitleDuration: 1.5

  #The subtitle and actionbar  to show when mentioned
  #Note that actionbar might not work if your version of Minecraft does not support it
  #Use {DiscordUser} for the ping-ers's discord name
  #Use {TextChannel} for the pinged channel name
  #Use {Guild} for the pinged guild name
  DiscordMentionSubtitle: "&9{DiscordUser} &fmentioned you in &9{TextChannel}!"
  DiscordMentionActionbar: ""

  #Highlight the mentioned playername for the player mentioned
  #Use {DiscordMention} for the highlighted player name
  MentionHighlight: "&9{DiscordMention}"

Messages:
  ReloadConfig: "&aICDiscordSRVAddon config has been reloaded!"
  ReloadTexture: "&aICDiscordSRVAddon reloading textures--- (See console for progress)"
  LinkExpired: "&cThis link has been expired! To view this link, please head over to the linked discord channel!"

Settings:
  CacheTimeout: 300
  EscapePlaceholdersSentFromDiscord: true
  EscapeDiscordMarkdownFormattingInItems: true

Resources:
  Language: en_us
  Order: []

Options:
  Updater: true