InventoryImage:
  #Whether or not to generate images for the item placeholder
  Item:
    Enabled: true
    #Show information about the item in a tooltip image instead of text
    UseTooltipImage: true
    #If UseTooltipImage is true, should the plugin attach tooltip image if the target item
    #is just a plain base item with no information worth showing
    UseTooltipImageOnBaseItem: false
    EmbedDisplay: 
      Single: "{Item}"
      Multiple: "{Item} x{Amount}"
    AlternateAirTexture: true
  #Whether or not to generate images for the inventory placeholder
  Inventory:
    Enabled: true
    #Use the player inventory gui template instead of the normal inventory template
    UsePlayerInventoryView: true
    EmbedColor: "#55FFFF"
    ShowExperienceLevel: true
  #Whether or not to generate images for the enderchest placeholder
  EnderChest:
    Enabled: true
    EmbedColor: "#FF55FF"

DeathMessage:
  #Show the weapon inside the death message if there is one
  ShowItems: true

Advancements:
  #Replace the advancement name from DiscordSRV with the actual display name
  CorrectAdvancementName: true
  #Show the icon of the advancement instead of the player head
  ChangeToItemIcon: true
  #Show the description of that advancement
  ShowDescription: true

HoverEventDisplay:
  #Whether or not to show hover event text
  Enabled: true
  #Whether or not to show the cursor image
  ShowCursorImage: true
  #Show information in a tooltip image instead of text
  UseTooltipImage: true
  #Which custom placeholder should have their hover event text ignored
  #This is a list of integer by indexes
  IgnoredPlaceholderIndexes: []

DiscordAttachments:
  #Whether or not to convert discord attachments from diguesting urls into clickable text in chat
  Convert: true
  Formatting: 
    Text: "&e[&b{FileName}&e]"
    ImageOriginal: " &a(Link)"
    Hover:
      Enabled: true
      HoverText: 
        - "&bClick to View"
      ImageOriginalHover: 
        - "&eOpen Original"
  #Whether or not to allow previwing images in game using maps
  ShowImageUsingMaps: true
  # When enabled, Only websites from the list below is allowed to be shown through in game maps
  RestrictImageUrl:
    Enabled: false
    Whitelist:
      - https://i.imgur.com
      - http://i.imgur.com
      - https://storage.googleapis.com
      - http://storage.googleapis.com
      - https://cdn.discordapp.com
      - http://cdn.discordapp.com
      - https://media.discordapp.net
      - http://media.discordapp.net
      - https://textures.minecraft.net
      - http://textures.minecraft.net
  Timeout: 86400
  PlaybackBar:
    Enabled: true
    FilledColor: "#FF0000"
    EmptyColor: "#938B86"


DiscordMention:
  #Link mentions through discordsrv linked accounts
  TranslateMentions: true

  #The sound to play when a player is mentioned
  #https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  MentionedSound: ENTITY_EXPERIENCE_ORB_PICKUP

  #The title to show when mentioned
  MentionedTitle: "&c&lMentioned"

  #How long should the title be shown when mentioned
  #Duration in seconds
  MentionedTitleDuration: 1.5

  #The subtitle and actionbar  to show when mentioned
  #Note that actionbar might not work if your version of Minecraft does not support it
  #Use {DiscordUser} for the ping-ers's discord name
  #Use {TextChannel} for the pinged channel name
  #Use {Guild} for the pinged guild name
  DiscordMentionSubtitle: "&9{DiscordUser} &fmentioned you in &9{TextChannel}!"
  DiscordMentionActionbar: ""

  #Highlight the mentioned playername for the player mentioned
  #Use {DiscordMention} for the highlighted player name
  MentionHighlight: "&9{DiscordMention}"

Messages:
  ReloadConfig: "&aICDiscordSRVAddon config has been reloaded!"
  ReloadTexture: "&aICDiscordSRVAddon reloading textures--- (See console for progress)"
  LinkExpired: "&cThis link has been expired! To view this link, please head over to the linked discord channel!"

Settings:
  CacheTimeout: 300
  EscapePlaceholdersSentFromDiscord: true
  EscapeDiscordMarkdownFormattingInItems: true
  ReducedAssetsDownloadInfo: false

Debug:
  PrintInfoToConsole: false

Resources:
  Language: en_us
  Order: []

Options:
  Updater: true