InventoryImage:
  #Whether or not to generate images for the item placeholder
  Item:
    EmbedDisplay: 
      Single: "{Item}"
      Multiple: "{Item} x{Amount}"
    Enabled: true
  #Whether or not to generate images for the inventory placeholder
  Inventory:
    #Use the player inventory gui template instead of the normal inventory template
    UsePlayerInventoryView: true
    EmbedColor: "#55FFFF"
    Enabled: true
  #Whether or not to generate images for the enderchest placeholder
  EnderChest:
    EmbedColor: "#FF55FF"
    Enabled: true

HoverEventDisplay:
  #Whether or not to show hover event text
  Enabled: true
  #Whether or not to show the cursor image
  ShowCursorImage: true
  #Which custom placeholder should have their hover event text ignored
  #This is a list of integer by indexes
  IgnoredPlaceholderIndexes: []

DiscordAttachments:
  #Whether or not to convert discord attachments from diguesting urls into clickable text in chat
  Convert: true
  Formatting: 
    Text: "&e[&b{FileName}&e]"
    ImageOriginal: " &a(Link)"
    Hover:
      Enabled: true
      HoverText: 
        - "&bClick to View"
      ImageOriginalHover: 
        - "&eOpen Original"
  #Whether or not to allow previwing images in game using maps
  ShowImageUsingMaps: true
  Timeout: 86400

Messages:
  ReloadConfig: "&aICDiscordSRVAddon config has been reloaded!"
  ReloadTexture: "&aICDiscordSRVAddon reloading textures--- (See console for progress)"
  LinkExpired: "&cThis link has been expired! To view this link, please head over to the linked discord channel!"

Settings:
  CacheTimeout: 300
  EscapePlaceholdersSentFromDiscord: true
  EscapeDiscordMarkdownFormattingInItems: true

Resources:
  Language: en_us
  Order: []

Options:
  Updater: true