InventoryImage:
  Item:
    EmbedDisplay: 
      Single: "{Item}"
      Multiple: "{Item} x{Amount}"
    Enabled: true
  Inventory:
    UsePlayerInventoryView: true
    EmbedColor: "#55FFFF"
    Enabled: true
  EnderChest:
    EmbedColor: "#FF55FF"
    Enabled: true

DiscordAttachments:
  Convert: true
  Formatting: 
    Text: "&e[&b{FileName}&e]"
    ImageOriginal: " &a(Link)"
    Hover:
      Enabled: true
      HoverText: "&bClick to View"
      ImageOriginalHover: "&eOpen Original"
  ShowImageUsingMaps: true
  Timeout: 86400

Messages:
  ReloadConfig: "&aICDiscordSRVAddon config has been reloaded!"
  ReloadTexture: "&aICDiscordSRVAddon reloading textures--- (See console for progress)"
  LinkExpired: "&cThis link has been expired! To view this link, please head over to the linked discord channel!"

Settings:
  CacheTimeout: 60
  EscapePlaceholdersSentFromDiscord: true
  EscapeDiscordMarkdownFormattingInItems: true

Resources:
  Order: []

Options:
  Updater: true

Translations:
  FilledMap:
    Id: "Id #{Id}"
    Scale: "Scaling at 1:{Scale}"
    Level: "(Level {Level}/4)"
  Durability:
    ToolTip: "Durability: {Remaining} / {Max}"
  Dye:
    Color: "Color: {Hex}"
  Unbreakable: 
    Name: Unbreakable
  Effects:
    NoEffect: "No Effects"
    Mappings:
      ABSORPTION: Absorption
      BAD_OMEN: Bad Omen
      BLINDNESS: Blindness
      CONDUIT_POWER: Conduit Power
      CONFUSION: Nausea
      DAMAGE_RESISTANCE: Resistance
      DOLPHINS_GRACE: "Dolphin\u0027s Grace"
      FAST_DIGGING: Haste
      FIRE_RESISTANCE: Fire Resistance
      GLOWING: Glowing
      HARM: Instant Damage
      HEAL: Instant Health
      HEALTH_BOOST: Health Boost
      HERO_OF_THE_VILLAGE: Hero of the Village
      HUNGER: Hunger
      INCREASE_DAMAGE: Strength
      INVISIBILITY: Invisibility
      JUMP: Jump Boost
      LEVITATION: Levitation
      LUCK: Luck
      NIGHT_VISION: Night Vision
      POISON: Poison
      REGENERATION: Regeneration
      SATURATION: Saturation
      SLOW: Slowness
      SLOW_DIGGING: Mining Fatigue
      SLOW_FALLING: Slow Falling
      SPEED: Speed
      UNLUCK: Bad Luck
      WATER_BREATHING: Water Breathing
      WEAKNESS: Weakness
      WITHER: Wither
  Enchantments:
    Mappings:
      PROTECTION_FIRE: Fire Protection
      DAMAGE_ALL: Sharpness
      ARROW_FIRE: Flame
      WATER_WORKER: Aqua Affinity
      ARROW_KNOCKBACK: Punch
      LOYALTY: Loyalty
      DEPTH_STRIDER: Depth Strider
      VANISHING_CURSE: Vanishing Curse
      DURABILITY: Unbreaking
      KNOCKBACK: Knockback
      LUCK: Luck Of The Sea
      BINDING_CURSE: Binding Curse
      LOOT_BONUS_BLOCKS: Fortune
      PROTECTION_ENVIRONMENTAL: Protection
      DIG_SPEED: Efficiency
      MENDING: Mending
      FROST_WALKER: Frost Walker
      LURE: Lure
      LOOT_BONUS_MOBS: Looting
      PIERCING: Piercing
      PROTECTION_EXPLOSIONS: Blast Protection
      DAMAGE_UNDEAD: Smite
      MULTISHOT: Multishot
      FIRE_ASPECT: Fire Aspect
      CHANNELING: Channeling
      SWEEPING_EDGE: Sweeping Edge
      THORNS: Thorns
      DAMAGE_ARTHROPODS: Bane Of Arthropods
      OXYGEN: Respiration
      RIPTIDE: Riptide
      SILK_TOUCH: Silk Touch
      QUICK_CHARGE: Quick Charge
      PROTECTION_PROJECTILE: Projectile Protection
      IMPALING: Impaling
      PROTECTION_FALL: Feather Falling
      ARROW_DAMAGE: Power
      ARROW_INFINITE: Infinity
      SOUL_SPEED: Soul Speed