InventoryImage:
  Item:
    Enabled: true
  Inventory:
    EmbedColor: "#55FFFF"
    Enabled: true
  EnderChest:
    EmbedColor: "#FF55FF"
    Enabled: true

Messages:
  ReloadConfig: "&aICDiscordSRVAddon config has been reloaded!"
  ReloadTexture: "&aICDiscordSRVAddon reloading textures... (See console for progress)"

Options:
  Updater: true